CREATE DATABASE LOCADORA_CARROS

CREATE TABLE "CARROS" (
	"COD_CARRO"	INTEGER NOT NULL,
	"COD_MODELO"	INTEGER NOT NULL,
	"ANO"	TEXT NOT NULL,
	"COR"	TEXT NOT NULL,
	"DESCRICAO"	TEXT NOT NULL,
	"OBSERVACAO"	TEXT,
	PRIMARY KEY("COD_CARRO" AUTOINCREMENT),
	FOREIGN KEY("COD_MODELO") REFERENCES "MODELOS"("COD_MODELO")
);

CREATE TABLE "CLIENTES" (
	"COD_CLIENTE"	INTEGER NOT NULL,
	"NOME"	TEXT NOT NULL,
	"EMAIL"	TEXT NOT NULL,
	"SENHA"	TEXT NOT NULL,
	PRIMARY KEY("COD_CLIENTE")
);

CREATE TABLE "LOCACOES" (
	"COD_LOCACAO"	INTEGER NOT NULL,
	"COD_CARRO"	INTEGER NOT NULL,
	"COD_CLIENTE"	INTEGER NOT NULL,
	"DATA_RETIRADA"	TEXT NOT NULL,
	"DATA_DEVOLUCAO"	TEXT NOT NULL,
	"VALOR"	REAL NOT NULL,
	"OBSERVACAO"	TEXT,
	FOREIGN KEY("COD_CLIENTE") REFERENCES "CLIENTES"("COD_CLIENTE"),
	FOREIGN KEY("COD_CARRO") REFERENCES "CARROS"("COD_CARRO"),
	PRIMARY KEY("COD_LOCACAO" AUTOINCREMENT)
);

CREATE TABLE "MARCAS" (
	"COD_MARCA"	INTEGER NOT NULL,
	"DESCRICAO"	TEXT NOT NULL,
	PRIMARY KEY("COD_MARCA" AUTOINCREMENT)
);

CREATE TABLE "MODELOS" (
	"COD_MODELO"	INTEGER NOT NULL,
	"COD_MARCA"	INTEGER NOT NULL,
	"DESCRICAO"	TEXT NOT NULL,
	PRIMARY KEY("COD_MODELO" AUTOINCREMENT),
	FOREIGN KEY("COD_MARCA") REFERENCES "MARCAS"("COD_MARCA")
);