--TRIGGER PRA DISPARAR MENSAGEM APOS ADICIONAR
CREATE TRIGGER TRG_CARRO_ADD 
	ON CARROS
	AFTER INSERT
	AS 
	BEGIN
		SELECT 'ADICIONADO'
	END


--STORED PROCEDURE PARA BUSCAR TODOS OS CLIENTES DO BANCO
CREATE PROCEDURE SelectAllCustomers
AS
SELECT * FROM CLIENTES
GO;