INSERT INTO CARROS (COD_MODELO, ANO, COR, DESCRICAO, OBSERVACAO)
VALUES 
(1,'2022','VERMELHO','...','...');

INSERT INTO CARROS (COD_MODELO, ANO, COR, DESCRICAO, OBSERVACAO)
VALUES 
(4,'2022','CINZA','...','...');

INSERT INTO CARROS (COD_MODELO, ANO, COR, DESCRICAO, OBSERVACAO)
VALUES 
(6,'2022','PRETO','...','...');

INSERT INTO CARROS (COD_MODELO, ANO, COR, DESCRICAO, OBSERVACAO)
VALUES 
(9,'2022','PRETO','...','...');
