--MITSUBISHI
INSERT INTO MODELOS (COD_MARCA,DESCRICAO) VALUES (16,'LANCER');
INSERT INTO MODELOS (COD_MARCA,DESCRICAO) VALUES (16,'ECLIPSE');
INSERT INTO MODELOS (COD_MARCA,DESCRICAO) VALUES (16,'PAJERO');

--NISSAN
INSERT INTO MODELOS (COD_MARCA,DESCRICAO) VALUES (23,'GT-R');
INSERT INTO MODELOS (COD_MARCA,DESCRICAO) VALUES (23,'370Z');

--FORD
INSERT INTO MODELOS (COD_MARCA,DESCRICAO) VALUES (17,'MUSTANG');
INSERT INTO MODELOS (COD_MARCA,DESCRICAO) VALUES (17,'KA');
INSERT INTO MODELOS (COD_MARCA,DESCRICAO) VALUES (17,'FOCUS');

--HONDA
INSERT INTO MODELOS (COD_MARCA,DESCRICAO) VALUES (19,'CIVIC');

